"""Update teacher profile for dyslexia fields

Revision ID: 8c856ee186bd
Revises: d867b127e15d
Create Date: 2025-07-10 16:06:21.666049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c856ee186bd'
down_revision: Union[str, Sequence[str], None] = 'd867b127e15d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher_profiles', sa.Column('dyslexia_approach', sa.String(), nullable=True))
    op.add_column('teacher_profiles', sa.Column('experience_years', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teacher_profiles', 'experience_years')
    op.drop_column('teacher_profiles', 'dyslexia_approach')
    # ### end Alembic commands ###
