"""add_questions_column_to_activities

Revision ID: 66b9aa242f5f
Revises: auto_add_quiz_answers
Create Date: 2025-08-02 16:19:14.810028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66b9aa242f5f'
down_revision: Union[str, Sequence[str], None] = 'auto_add_quiz_answers'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('questions', sa.Text(), nullable=True))
    op.alter_column('activities', 'title',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activities', 'title',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('activities', 'questions')
    # ### end Alembic commands ###
